# speedcrunch

set(speedcrunch_HEADERS
#variant/variantdata.hxx
#variant/variant.hxx
#variant/real.hxx
#3rdparty/util/binreloc.h
base/constants.hxx
base/evaluator.hxx
#base/functions.hxx
#base/settings.hxx
gui/aboutbox.hxx
gui/autohidelabel.hxx
gui/constantsdock.hxx
gui/deletevardlg.hxx
gui/editor.hxx
gui/functionsdock.hxx
gui/historydock.hxx
gui/insertfunctiondlg.hxx
gui/insertvardlg.hxx
gui/keypad.hxx
gui/result.hxx
gui/tipwidget.hxx
gui/variablesdock.hxx
gui/mainwindow.hxx
#math/floatcommon.h
#math/floatconfig.h
#math/floatconst.h
#math/floatconvert.h
#math/floaterf.h
#math/floatexp.h
#math/floatgamma.h
#math/floathmath.h
#math/floatio.h
#math/floatipower.h
#math/floatlog.h
#math/floatlogic.h
#math/floatlong.h
#math/floatnum.h
#math/floatpower.h
#math/floatseries.h
#math/floattrig.h
#math/hmath.hxx
#math/number.h
)

set(speedcrunch_SOURCES
variant/variantdata.cpp
variant/variant.cpp
variant/real.cpp
variant/initvariant.cpp
3rdparty/util/binreloc.c
base/constants.cpp
base/evaluator.cpp
base/functions.cpp
base/settings.cpp
gui/aboutbox.cpp
gui/autohidelabel.cpp
gui/constantsdock.cpp
gui/deletevardlg.cpp
gui/editor.cpp
gui/functionsdock.cpp
gui/historydock.cpp
gui/insertfunctiondlg.cpp
gui/insertvardlg.cpp
gui/keypad.cpp
gui/result.cpp
gui/tipwidget.cpp
gui/variablesdock.cpp
gui/mainwindow.cpp
main/main.cpp
math/floatcommon.c
math/floatconst.c
math/floatconvert.c
math/floaterf.c
math/floatexp.c
math/floatgamma.c
math/floathmath.c
math/floatio.c
math/floatipower.c
math/floatlog.c
math/floatlogic.c
math/floatlong.c
math/floatnum.c
math/floatpower.c
math/floatseries.c
math/floattrig.c
math/hmath.cpp
math/number.c
)


# regression test for HMath
set(testhmath_SOURCES
math/floatcommon.c
math/floatconst.c
math/floatconvert.c
math/floaterf.c
math/floatexp.c
math/floathmath.c
math/floatgamma.c
math/floatio.c
math/floatipower.c
math/floatlog.c
math/floatlogic.c
math/floatlong.c
math/floatnum.c
math/floatpower.c
math/floatseries.c
math/floattrig.c
math/hmath.cpp
math/number.c
test/testhmath.cpp
)


# regression test for Evaluator
#set(testevaluator_SOURCES
#base/evaluator.hxx
#)
#set(testevaluator_SOURCES
#base/evaluator.cpp
#base/functions.cpp
#base/variant.cpp
#bison/exprparser.c
#math/floatcommon.c
#math/floatconst.c
#math/floatconvert.c
#math/floaterf.c
#math/floatexp.c
#math/floathmath.c
#math/floatgamma.c
#math/floatio.c
#math/floatipower.c
#math/floatlog.c
#math/floatlogic.c
#math/floatlong.c
#math/floatnum.c
#math/floatpower.c
#math/floatseries.c
#math/floattrig.c
#math/numdata.cpp
#math/hmath.cpp
#math/number.c
#test/testevaluator.cpp
#)


# regression test for floatnum
set(testfloatnum_SOURCES
math/floatcommon.c
math/floatconst.c
math/floatconvert.c
math/floaterf.c
math/floatexp.c
math/floathmath.c
math/floatgamma.c
math/floatio.c
math/floatipower.c
math/floatlog.c
math/floatlogic.c
math/floatlong.c
math/floatnum.c
math/floatpower.c
math/floatseries.c
math/floattrig.c
math/number.c
test/testfloatnum.c
)
